baseURL = "https://sk1.jsiu.dev"
theme   = "sk1"
title   = "SK1"

[Params]
maintype = "post"
subtitle = "A Hugo Theme"

[menu]
	[[menu.main]]
	identifier = "about"
	name       = "About"
	url        = "/about/"
	weight     = 10
	[[menu.main]]
	name = "Tags"
	url  = "/tags/"
